# Generated by Django 4.0.2 on 2022-02-19 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('equipe', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('feminino', 'Feminino'), ('masculino', 'Masculino')], default='feminino', max_length=50)),
                ('peso', models.IntegerField(default=0)),
                ('idade', models.IntegerField(default=0)),
                ('graduacao', models.CharField(choices=[('faixabranca', 'Faixa Branca'), ('faixaazul', 'Faixa Azul'), ('faixaroxa', 'Faixa Roxa'), ('faixamarrom', 'Faixa Marrom'), ('faixapreta', 'Faixa Preta')], default='faixabranca', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('promotor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
